### ISSUE TITLE
ProdigyCape  Error

### ISSUE THREAD

**Issue by WolfPack206567** [corentingosselin/ProdigyCape#12]
[18:59:40] [Server thread/INFO]: This server is running Paper version git-Paper-36 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 0db72ac)

[18:59:42] [Server thread/INFO]: Using 4 threads for Netty based IO

[18:59:42] [Server thread/INFO]: Server Ping Player Sample Count: 12

[18:59:42] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.

We recommend installing the spark profiler as a replacement: https://spark.lucko.me/

For more information please visit: https://github.com/PaperMC/Paper/issues/8948

[18:59:43] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads

[18:59:43] [Server thread/INFO]: Default game type: SURVIVAL

[18:59:43] [Server thread/INFO]: Generating keypair

[18:59:43] [Server thread/INFO]: Starting Minecraft server on *:25565

[18:59:44] [Server thread/INFO]: Using epoll channel type

[18:59:44] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.

[18:59:44] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.

[18:59:45] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.10.2

[18:59:45] [Server thread/INFO]: [ViaVersion] ViaVersion 4.10.2 is now loaded. Registering protocol transformers and injecting...

[18:59:47] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...

[18:59:47] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections

[18:59:48] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.1-SNAPSHOT-689

[18:59:48] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.

[18:59:52] [Server thread/INFO]: [Vault] Loading server plugin Vault v1.7.3-b131

[18:59:52] [Server thread/INFO]: [packetevents] Loading server plugin packetevents v2.3.0

[19:00:03] [Server thread/INFO]: [ProdigyCape] Loading server plugin ProdigyCape v1.0.1-SNAPSHOT

[19:00:04] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it

[19:00:04] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.1-SNAPSHOT-689

[19:00:04] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131

[19:00:04] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.

[19:00:05] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131

[19:00:05] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

[19:00:05] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.

[19:00:05] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.

[19:00:05] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.

[19:00:05] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.

[19:00:05] [Server thread/INFO]: Preparing level "world"

[19:00:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld

[19:00:07] [Server thread/INFO]: Time elapsed: 2 ms

[19:00:07] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether

[19:00:07] [Server thread/INFO]: Time elapsed: 4 ms

[19:00:07] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end

[19:00:07] [Server thread/INFO]: Time elapsed: 4 ms

[19:00:07] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.10.2

[19:00:07] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.20.5-1.20.6 (766)

[19:00:07] [Server thread/WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version!

[19:00:07] [Server thread/WARN]: [ViaVersion] Please remember that ViaVersion only adds support for versions newer than the server version.

[19:00:07] [Server thread/WARN]: [ViaVersion] If you need support for older versions you may need to use one or more ViaVersion addons too.

[19:00:07] [Server thread/WARN]: [ViaVersion] In that case please read the ViaVersion resource page carefully or use https://viaversion.com/setup

[19:00:07] [Server thread/WARN]: [ViaVersion] and if you're still unsure, feel free to join our Discord-Server for further assistance.

[19:00:07] [Server thread/INFO]: [packetevents] Enabling packetevents v2.3.0

[19:00:07] [packetevents-update-check-thread/INFO]: [packetevents] Checking for updates, please wait...

[19:00:07] [Server thread/INFO]: [ProdigyCape] Enabling ProdigyCape v1.0.1-SNAPSHOT

[19:00:07] [Server thread/INFO]: PaperMC detected 1.20.6-R0.1-SNAPSHOT

[19:00:07] [Server thread/ERROR]: Error occurred while enabling ProdigyCape v1.0.1-SNAPSHOT (Is it up to date?)

java.lang.UnsupportedClassVersionError: fr/cocoraid/prodigycape/support/NMS_1_20_6 has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0

at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]

at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]

at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]

at ProdigyCape-1.0.1-SNAPSHOT.jar/fr.cocoraid.prodigycape.nms.NmsHandlerFactory.getHandler(NmsHandlerFactory.java:28) ~[ProdigyCape-1.0.1-SNAPSHOT.jar:?]

at ProdigyCape-1.0.1-SNAPSHOT.jar/fr.cocoraid.prodigycape.ProdigyCape.onEnable(ProdigyCape.java:60) ~[ProdigyCape-1.0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-36]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-36]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-36]

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-36]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

[19:00:07] [Server thread/INFO]: [ProdigyCape] Disabling ProdigyCape v1.0.1-SNAPSHOT

[19:00:07] [Server thread/ERROR]: Error occurred while disabling ProdigyCape v1.0.1-SNAPSHOT

java.lang.NullPointerException: Cannot invoke "fr.cocoraid.prodigycape.manager.ProdigyManager.getProdigyPlayers()" because "this.prodigyManager" is null

at ProdigyCape-1.0.1-SNAPSHOT.jar/fr.cocoraid.prodigycape.ProdigyCape.onDisable(ProdigyCape.java:239) ~[ProdigyCape-1.0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:git-Paper-36]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:git-Paper-36]

at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:git-Paper-36]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-36]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-36]

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-36]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

[19:00:08] [Server thread/INFO]: Running delayed init tasks

[19:00:08] [Craft Scheduler Thread - 2 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!

[19:00:08] [Server thread/INFO]: Done (27.763s)! For help, type "help"

[19:00:08] [Server thread/INFO]: Timings Reset

[19:00:08] [Craft Scheduler Thread - 1 - Vault/INFO]: [Vault] Checking for Updates ...

[19:00:08] [Craft Scheduler Thread - 1 - Vault/INFO]: [Vault] No new version available

[19:00:08] [packetevents-update-check-thread/INFO]: [packetevents] You are on the latest released version of packetevents. Your build: (2.3.0)

**Comment by corentingosselin** [comment]
Do you use java 21 or 22 for the server ?

**Comment by WolfPack206567** [comment]
I use a host called MineFort and i don't know my java verison

**Comment by corentingosselin** [comment]
you can try this plugin: https://www.spigotmc.org/resources/java-version-checker-tool.34827/
