### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by jurvyy** [corentingosselin/ProdigyCape#25]
Version: 1.20.6 Purpur
Plugin version: 1.0.1

[11:01:20] [Server thread/INFO]: [ProdigyCape] Enabling ProdigyCape v1.0.1-SNAPSHOT
[11:01:20] [Server thread/INFO]: PaperMC detected 1.20.6-R0.1-SNAPSHOT
[11:01:20] [Server thread/ERROR]: Error occurred while enabling ProdigyCape v1.0.1-SNAPSHOT (Is it up to date?)
java.lang.UnsupportedClassVersionError: fr/cocoraid/prodigycape/support/NMS_1_20_6 has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at ProdigyCape-1.0.1-SNAPSHOT.2.jar/fr.cocoraid.prodigycape.nms.NmsHandlerFactory.getHandler(NmsHandlerFactory.java:28) ~[ProdigyCape-1.0.1-SNAPSHOT.2.jar:?]
	at ProdigyCape-1.0.1-SNAPSHOT.2.jar/fr.cocoraid.prodigycape.ProdigyCape.onEnable(ProdigyCape.java:60) ~[ProdigyCape-1.0.1-SNAPSHOT.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[?:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:01:20] [Server thread/INFO]: [ProdigyCape] Disabling ProdigyCape v1.0.1-SNAPSHOT
[11:01:20] [Server thread/ERROR]: Error occurred while disabling ProdigyCape v1.0.1-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "fr.cocoraid.prodigycape.manager.ProdigyManager.getProdigyPlayers()" because "this.prodigyManager" is null
	at ProdigyCape-1.0.1-SNAPSHOT.2.jar/fr.cocoraid.prodigycape.ProdigyCape.onDisable(ProdigyCape.java:239) ~[ProdigyCape-1.0.1-SNAPSHOT.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[?:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-DEV-86ad0b3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by corentingosselin** [comment]
#12 Can you please give me your java server version ?

**Comment by max1mde** [comment]
He does not have to check
It literally says the version in that error:
`has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0`

**Comment by max1mde** [comment]
![image](https://github.com/corentingosselin/ProdigyCape/assets/114857048/96d0922b-4b77-482b-89ba-c488f64c7841)

**Comment by corentingosselin** [comment]
Lol of course ^^ I knew that compiling the project to latest java was a mistake 
Gonna fix this

**Comment by max1mde** [comment]
Use JDK 17

**Comment by corentingosselin** [comment]
fixed with entitylib migration
