### ISSUE TITLE
ProdigyCape and ProtocolLib not work

### ISSUE THREAD

**Issue by WolfPack206567** [corentingosselin/ProdigyCape#4]
Applying patches

Starting org.bukkit.craftbukkit.Main

*** Warning, you've not updated in a while! *** *** Please download a new build as per instructions from https://papermc.io/downloads/paper ***

System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS) Host: Linux 5.4.0-67-generic (amd64) Loading libraries, please wait...

[20:47:25 INFO]: [ReobfServer] Remapping server...

[20:47:31 INFO]: [ReobfServer] Done remapping server in 6806ms.

[20:47:31 INFO]: [PluginRemapper] Remapping plugin 'plugins/ProtocolLib.jar'...

[20:47:31 INFO]: [PluginRemapper] Remapping plugin 'plugins/ProdigyCape-1.0.1-SNAPSHOT.jar'...

[20:47:31 INFO]: [PluginRemapper] Remapping plugin 'plugins/Vault.jar'...

[20:47:32 INFO]: [PluginRemapper] Done remapping plugin 'plugins/Vault.jar' in 542ms.

[20:47:32 INFO]: [PluginRemapper] Done remapping plugin 'plugins/ProdigyCape-1.0.1-SNAPSHOT.jar' in 821ms.

[20:47:33 INFO]: [PluginRemapper] Done remapping plugin 'plugins/ProtocolLib.jar' in 1694ms.

[20:47:38 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]

[20:47:41 INFO]: Loaded 1175 recipes

[20:47:41 INFO]: Loaded 1276 advancements

[20:47:41 INFO]: Starting minecraft server version 1.20.6

[20:47:41 INFO]: Loading properties

[20:47:41 INFO]: This server is running Paper version git-Paper-36 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 0db72ac)

[20:47:43 INFO]: Using 4 threads for Netty based IO

[20:47:43 INFO]: Server Ping Player Sample Count: 12

[20:47:43 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads

[20:47:43 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future. We recommend installing the spark profiler as a replacement: https://spark.lucko.me/ For more information please visit: https://github.com/PaperMC/Paper/issues/8948

[20:47:43 INFO]: Default game type: SURVIVAL

[20:47:43 INFO]: Generating keypair

[20:47:43 INFO]: Starting Minecraft server on *:25565

[20:47:44 INFO]: Using epoll channel type

[20:47:44 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ProdigyCape-1.0.1-SNAPSHOT.jar' in folder 'plugins/.paper-remapped' org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.6.jar:git-Paper-36] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:git-Paper-36] at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:git-Paper-36] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:git-Paper-36] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:git-Paper-36] at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:508) ~[paper-1.20.6.jar:git-Paper-36] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[paper-1.20.6.jar:git-Paper-36] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-36] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-36] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener at java.base/java.lang.Class.forName0(Native Method) ~[?:?] at java.base/java.lang.Class.forName(Class.java:534) ~[?:?] at java.base/java.lang.Class.forName(Class.java:513) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:git-Paper-36] ... 9 more Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] at java.base/java.lang.Class.forName0(Native Method) ~[?:?] at java.base/java.lang.Class.forName(Class.java:534) ~[?:?] at java.base/java.lang.Class.forName(Class.java:513) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.6.jar:git-Paper-36] ... 9 more

[20:47:44 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131

[20:47:44 INFO]: [ViaVersion] Loading server plugin ViaVersion v4.10.2

[20:47:44 INFO]: [ViaVersion] ViaVersion 4.10.2 is now loaded. Registering protocol transformers and injecting...

[20:47:49 INFO]: [ViaVersion] Loading block connection mappings ...

[20:47:50 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections

[20:47:51 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.1-SNAPSHOT-689

[20:47:51 WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.

[20:47:53 INFO]: Server permissions file permissions.yml is empty, ignoring it

[20:47:53 INFO]: [Vault] Enabling Vault v1.7.3-b131

[20:47:53 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.

[20:47:53 INFO]: [Vault] Enabled Version 1.7.3-b131

[20:47:53 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.1-SNAPSHOT-689

[20:47:53 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE! [20:47:53 WARN]: The server will make no attempt to authenticate usernames. Beware.

[20:47:53 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.

[20:47:53 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.

[20:47:53 WARN]: To change this, set "online-mode" to "true" in the server.properties file.

[20:47:53 INFO]: Preparing level "world"

[20:47:54 INFO]: Preparing start region for dimension minecraft:overworld

[20:47:54 INFO]: Time elapsed: 1 ms

[20:47:54 INFO]: Preparing start region for dimension minecraft:the_nether

[20:47:54 INFO]: Time elapsed: 1 ms

[20:47:54 INFO]: Preparing start region for dimension minecraft:the_end

[20:47:54 INFO]: Time elapsed: 0 ms

[20:47:54 INFO]: [ViaVersion] Enabling ViaVersion v4.10.2

[20:47:54 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.5-1.20.6 (766)

[20:47:54 WARN]: [ViaVersion] ViaVersion does not have any compatible versions for this server version! [20:47:54 WARN]: [ViaVersion] Please remember that ViaVersion only adds support for versions newer than the server version.

[20:47:54 WARN]: [ViaVersion] If you need support for older versions you may need to use one or more ViaVersion addons too. [20:47:54 WARN]: [ViaVersion] In that case please read the ViaVersion resource page carefully or use https://viaversion.com/setup

[20:47:54 WARN]: [ViaVersion] and if you're still unsure, feel free to join our Discord-Server for further assistance.

[20:47:54 INFO]: Running delayed init tasks

[20:47:54 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!

[20:47:54 INFO]: Done (13.225s)! For help, type "help"

[20:47:54 INFO]: Timings Reset

[20:47:54 INFO]: [Vault] Checking for Updates ...

[20:47:55 INFO]: [Vault] No new version available

**Comment by WolfPack206567** [comment]
by the way i using PaperMC 1.20.6

**Comment by corentingosselin** [comment]
You need the latest version of protocollib here: https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/
don't download the protocollib jar from spigot

Also you paper spigot is outdated: *** Warning, you've not updated in a while! *** *** Please download a new build as per instructions from https://papermc.io/downloads/paper ***

**Comment by corentingosselin** [comment]
This actually the plugin fault, bug fixed
